### PR TITLE
Proposed Favicon

### PR DESCRIPTION
**Pull request by rhnvrm**
based on http://www.catb.org/hacker-emblem/

### CODE REVIEW

**Comment by avinassh** [comment]
wow dude, so quick!

Thanks! :D

**Comment by avinassh** [comment]
Why are you not so active in slack these days

**Comment by rhnvrm** [comment]
@avinassh: Messed up slack on my machine few months ago, setting it up again. Just installed ScudCloud so will be back on slack from tomorrow :+1:

**Comment by avinassh** [comment]
👍

**Pull request merged**
